apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tests
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tests
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
          - name: postgres
            containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: tests
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: tests
spec:
  storageClassName: manual
  volumeName: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi