{{- if ne .Values.ingress.useIngressController true }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak-ingress
  namespace: {{ .Release.namespace }}
  labels:
    apps: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: {{ .Values.keycloak.deployment.port }}
      targetPort: {{ .Values.keycloak.deployment.port }}
{{- end }}