{{- if ne .Values.ingress.useIngressController true }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak-ingress
  namespace: {{ .Release.namespace }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: keycloak
  ports:
    - port: {{ .Values.keycloak.deployment.port }}
      targetPort: {{ .Values.keycloak.deployment.port }}
{{- end }}