apiVersion: v1
kind: Service
metadata:
  name: infinispan
  namespace: {{ .Release.Namespace }}
  labels:
    app: infinispan
spec:
  ports:
    - name: infinispan
      protocol: TCP
      port: {{ .Values.infinispan.deployment.port }}
      targetPort: {{ .Values.infinispan.deployment.port }}
  selector:
    app: infinispan
  type: ClusterIP