{{- if .Values.infinispan.storage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinispan
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.infinispan.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.infinispan.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infinispan
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  volumeName: infinispan
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.infinispan.storage.capacity }}
{{- end }}