apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  ports:
    - name: keycloak
      protocol: TCP
      port: {{ .Values.keycloak.deployment.port }}
      targetPort: {{ .Values.keycloak.deployment.port }}
  selector:
    app: keycloak
  type: ClusterIP