apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.keycloak.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.keycloak.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  volumeName: keycloak
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.storage.capacity }}