apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.deployment.port }}
      targetPort: {{ .Values.postgres.deployment.port }}
  selector:
    app: postgres
  type: ClusterIP