{{- if .Values.postgres.storage }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  volumeName: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.capacity }}
{{- end }}